# 数据操作

视频地址：https://www.bilibili.com/video/BV1CV411Y7i4?spm_id_from=333.999.0.0


## 导入torch

In [7]:
import torch

## 生成一个一维张量
>`torch.arange(起点, 终点, step=相邻点间隔大小)`

In [8]:
# 张量X
x = torch.arange(0,12,1)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## 自定义张量赋值
>自定义张量：`torch.tensor([ [],[] ])`

In [19]:
# 灰度图像 3*3图像 格式 [行[列]]
a = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("灰度图像 3*3图像 格式 [行[列]]")
print(a)


# 彩色图像 2*3 图像 格式 [行[列[灰度值]]]
b = torch.tensor([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[4,5,6],[4,5,6],[4,5,6]]
])
print("彩色图像 2*3 图像 格式 [行[列[灰度值]]]")
print(b)

灰度图像 3*3图像 格式 [行[列]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
彩色图像 2*3 图像 格式 [行[列[灰度值]]]
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])


## 查询张量的形状和元素的总数
>查询张量形状：`张量变量.shape`  
>查询元素总数：`张量变量.numel()`


In [14]:
x = torch.arange(0,12,1)

# 张量形状
print("张量形状")
print(x.shape)

# 张量元素个数
print("张量元素总个数")
print(x.numel())

张量形状
torch.Size([12])
张量元素总个数
12


## 改变一个张量形状，不改变其元素数量和元素值
>改变张量形状：`张量变量.reshape(第一层元素数量, 第二层元素数量, 第三层元素数量)`

In [16]:
x = torch.arange(0,12,1)
print(x)

# 把1维张量x转变为三维张量
X = x.reshape(1,3,4)
print(X)

# 把1维张量x转变为二维张量，三行四列
X = x.reshape(3,4)
print(X)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## 张量连接 
>把维度相同的张量合并（维度不增加）：`torch.cat((张量1,张量2),dim=0)` dim=0增加行，dim=1增加列

In [31]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
print(X)

Y = torch.tensor([
    [2, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])
print(Y)

# 张量连接dim=0 增加行
print('张量连接dim=0 增加行')
print(torch.cat((X,Y),dim=0))

# 张量连接dim=1 增加列
print('张量连接dim=0 增加列')
print(torch.cat((X,Y),dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
张量连接dim=0 增加行
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
张量连接dim=0 增加列
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## numpy张量与torch张量转换
>torch转numpy：`张量变量.numpy()`  
>numpy转torch：`torch.tensor(张量变量)`

In [5]:
X = torch.tensor([
    [2, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])
print(X)

# 把torch转为numpy
Y = X.numpy()
print(Y)

# 把numpy转为torch
Z = torch.tensor(Y)
print(Z)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
[[2 1 4 3]
 [1 2 3 4]
 [4 3 2 1]]
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
