# 线性代数（torch基础）

视频地址：https://www.bilibili.com/video/BV1eK4y1U7Qy?p=2

`import torch`


In [5]:
import torch

x = torch.arange(4)

print(x)

tensor([0, 1, 2, 3])


## 访问张量

>通过索引访问张量一个元素：
>>代码：`张量变量.[数字下标]`

>访问张量长度：
>>代码：`len(张量变量)`  

>访问张量形状：
>>代码：`张量变量.shape`

In [6]:
# 访问张量元素
x[3]

tensor(3)

In [7]:
# 访问张量长度
len(x)

4

In [10]:
# 访问张量形状

y = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,9,0],[1,2,4]]
])

y.shape

torch.Size([2, 2, 3])

## 矩阵操作

>创建矩阵：
>>代码：`torch.tensor([ [], [] ])`  
>>说明：最内层为行，接着为列

>指定分量大小创建矩阵：
>>代码：`张量变量.reshape(最外层元素个数, 内层元素个数)`

>矩阵转置：
>>代码：`矩阵变量.T`

In [13]:
import torch

A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [14]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 矩阵运算

>矩阵克隆
>>代码：`矩阵变量B = 矩阵变量A.clone()`  
>>说明：通过分配新内存，为矩阵生成副本

>两个矩阵运算
>>两矩阵对应元素相加：`矩阵变量A + 矩阵变量 B`  
>>两矩阵对应元素相乘：`矩阵变量A * 矩阵变量 B`

In [17]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()

print('A:', A)
print('B:', B)

A: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
B: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [18]:
# 两矩阵对应元素相加
A + B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [19]:
# 两矩阵对应元素相乘
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

## 降维

>张量元素求和
>>代码：`张量变量.sum()`

>沿轴通过求和降低张量维度
>>汇总列元素降维：`张量变量.sum(axis=0)`  
>>汇总行元素降维：`张量变量.sum(axis=1)`  
>>对矩阵的所有元素进⾏求和:`张量变量.sum(axis=[0,1])` 

>非降维求和
>>代码：`张量变量.sum(axis=0, keepdims=True)`

In [1]:
import torch

x = torch.arange(4, dtype=torch.float32)

x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [5]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
print(A)

x = A.sum(axis=0)
print(x)

y = A.sum(axis=1)
print(y)

z = A.sum(axis=1, keepdims=True)
print(z)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([40., 45., 50., 55.])
tensor([ 6., 22., 38., 54., 70.])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
